version: "3.7"
services:       
        # Php+Nginx Service
        php-fpm:
                build:
                        context: ./
                        dockerfile: docker/php-fpm/Dockerfile
                image: administrator_php-fpm
        
        # local
        lcl:
                build:
                        context: ./
                        dockerfile: docker/local/Dockerfile
                image: administrator_lcl:latest
                container_name: administrator_lcl
                tty: true
                ports: 
                        - 10001:80
                env_file: 
                        - administrator-deploy/.env.local
                environment: 
                        - APP_ENV=local
                        - APP_DEBUG=true
                volumes: 
                        - /app/vendor/
                        - /app/node_modules/
                        - /app/public/assets/js/
                        - /app/public/assets/css/
                        - /app/storage
                        - .:/app/
                depends_on: 
                        - db
                        - redis
                links:
                        - db
                        - redis
        # mysql Service
        db:
                image: mysql:5.7.32
                container_name: administrator_db
                ports: 
                        - 3306:3306
                volumes:
                        - administrator_dbdata:/var/lib/mysql
                        - ./mysql/my.cnf:/etc/mysql/my.cnf
                environment:
                        - MYSQL_DATABASE=administrator
                        - MYSQL_ROOT_PASSWORD=administrator
        # Redis Service
        redis:
                image: redis:alpine
                container_name: administrator_redis
                ports: 
                        - "6379"
                        
volumes:
        administrator_dbdata: